function roi_file = resample_roi(roi_file,wmean_file)

% Resample the provided ROI file to the voxel geometry of the mean
% functional. No transformation applied, so both must be in MNI space.
flags = struct( ...
        'mask',true, ...
        'mean',false, ...
        'interp',0, ...
        'which',1, ...
        'wrap',[0 0 0], ...
        'prefix','r' ...
        );
spm_reslice({wmean_file; roi_file},flags);
[~,n,e] = fileparts(atlas_file);
roi_file = fullfile(out_dir,['r' n e]);
