% SPM12 needs to be in the path also
addpath(genpath('.'))

fmri_modularity( ...
	'magick_path','/usr/local/bin', ...
	'community_file',which('eight_networks_tcorr05_2level_43_0840rois_3study.csv'), ...
	'connmat_file','../INPUTS/connmat.csv', ...
	'roiinfo_file','../INPUTS/roiinfo.csv', ...
	'roi_file','../INPUTS/roi.nii.gz', ...
	'project','UNK_PROJ', ...
	'subject','UNK_SUBJ', ...
	'session','UNK_SESS', ...
	'scan','Project-x-Subject-x-Session-x-UNK_SCAN-x-Assessor', ...
	'out_dir','../OUTPUTS' ...
	);

% 	'scan','UNK_SCAN', ...
